### ISSUE TITLE
photon boundary condition / RSA

### ISSUE THREAD

**Issue by xzackli** [xzackli/Bolt.jl#48]
As discussed in #44 by @jmsull, we appear to need something like CLASS's RSA to avoid unphysical oscillations from reflections off the boundary condition. 

[CLASS paper II](https://arxiv.org/pdf/1104.2933.pdf) has a description in the synchronous gauge, and [Doran+05](https://arxiv.org/pdf/astro-ph/0503277.pdf) has a similar approach for the Newtonian gauge. Taking the equations from Doran is the lowest effort option (no need to transform any variables), but I definitely need to read these papers in more detail.

**Comment by jmsull** [comment]
I tried the Newtonian RSA as it is implemented in CLASS, and I think once it is working it will do something that is not totally wrong (late-time photon/ur huge oscillation are gone), though I still need to iron out some details. However, I am running into a technical issue with DifferentialEquations.jl, which is probably just due to my lack of experience with these tools, but I will describe it below (I know @xzackli may still be busy as mentioned, but maybe @marius311 has some advice as well).

For RSA I use the (default CLASS) two-condition conformal time switch (one on decoupling involving \eta \tau' and one on the mode k \eta) such that after this time no photon or ur ODEs are evolved. Instead, the relevant components of u (\Theta, \scrN) are simply supplied algebraically according to the RSA equations. This all seems to work fine internal to the hierarchy!() call in perturbations.jl.

However, it seems u is discarded at every timestep, and the values of \Theta, \scrN are incremented by the solver using the value of du and the timestep (as usually we would want for the hierarchy). So for all times after the RSA switch, the actual outputted result by the solver for \Theta, \scrN is total garbage, even though internally it would seem things are working fine (print statements and other perturbation variables look okay). This would not be a problem if we could just save u, but this doesn't seem possible in DifferentialEquations.jl in the way we are using it currently.

I looked around in the docs, and it seems you can, for example, use saving callbacks to save u at specified steps. But this requires the integrator to descend somehow from the [DEIntegrator](https://diffeq.sciml.ai/stable/basics/integrator/) of DifferentialEquations.jl, which the current PerturbationIntegrator @xzackli defined in perturbations.jl does not appear related to(?). Similarly, if we were using the DEIntegrator functionality we might also query the timestep internally and back out the necessary du to get the u we want (though this is not ideal obviously).

I guess my question is, is there some way to easily get the algebraically-supplied u to be returned properly as the final result of the solver, or is the next step to tie PerturbationIntegrator to the DEIntegrator so we can use callbacks to get u?

**Comment by jmsull** [comment]
I have (clunkily) figured this out for now (212824d) - the perturbations evolve using the RSA equations after the RSA switch is triggered, but the u that comes out of this is not right for the massless species. I wrote a separate function rsa_perts!() that takes as input the evolved perturbation vector and returns the RSA expressions for the massless perturbations (which were being evolved anyways).

For now I have wrapped this in an rsa_boltsolve() function, which is just boltsolve but with the extra step of rsa post-processing described above so the user gets out a vector u that is correct and incorporates RSA.

Closing this since things seem to work - will put some plots in the PR.
